CRITICAL - 2025-08-06 14:13:41 --> ErrorException: Undefined array key ""
[Method: GET, Route: equipos]
in APPPATH\Views\equipos.php on line 96.
 1 APPPATH\Views\equipos.php(96): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key ""', 'C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\equipos.php', 96)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\equipos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('equipos', [], true)
 5 APPPATH\Controllers\EquipoController.php(12): view('equipos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:26:44 --> ErrorException: Undefined array key ""
[Method: GET, Route: equipos]
in APPPATH\Views\equipos.php on line 96.
 1 APPPATH\Views\equipos.php(96): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key ""', 'C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\equipos.php', 96)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\repaso0408\\repaso\\app\\Views\\equipos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('equipos', [], true)
 5 APPPATH\Controllers\EquipoController.php(12): view('equipos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 14:54:22 --> mysqli_sql_exception: Column 'empleado_id' cannot be null in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `em...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `em...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `em...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 14:54:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
[Method: POST, Route: agregarEmpleado]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:54:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:54:22 --> [Caused by] mysqli_sql_exception: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 14:54:54 --> mysqli_sql_exception: Column 'empleado_id' cannot be null in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `em...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `em...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `em...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 14:54:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
[Method: POST, Route: agregarEmpleado]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:54:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:54:54 --> [Caused by] mysqli_sql_exception: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 14:55:50 --> mysqli_sql_exception: Column 'empleado_id' cannot be null in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `em...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `em...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `em...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 14:55:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
[Method: POST, Route: agregarEmpleado]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:55:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:55:50 --> [Caused by] mysqli_sql_exception: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 14:55:53 --> mysqli_sql_exception: Column 'empleado_id' cannot be null in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `em...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `em...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `em...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 14:55:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
[Method: POST, Route: agregarEmpleado]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:55:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:55:53 --> [Caused by] mysqli_sql_exception: Column 'empleado_id' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (NULL, NULL, \'25\', NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EmpleadoController.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 14:57:10 --> mysqli_sql_exception: Duplicate entry '994' for key 'PRIMARY' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `eq...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `eq...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `eq...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `eq...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EquipoController.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 14:57:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '994' for key 'PRIMARY'
[Method: POST, Route: agregarEquipo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:57:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '994' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'994\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'994\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 14:57:10 --> [Caused by] mysqli_sql_exception: Duplicate entry '994' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'994\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'994\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'994\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 15:03:16 --> mysqli_sql_exception: Duplicate entry '80' for key 'PRIMARY' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `eq...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `eq...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `eq...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `eq...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EquipoController.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 15:03:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '80' for key 'PRIMARY'
[Method: POST, Route: agregarEquipo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:03:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '80' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'80\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'80\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:03:16 --> [Caused by] mysqli_sql_exception: Duplicate entry '80' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'80\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'80\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (\'80\', \'6550\', \'8\', \'Equipo portátil para capacitadores\', \'2022-09-28\', \'18745.00\', \'1\', \'444\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `equipos` (`equipo_id`, `no_serie`, `marca_id`, `descripcion`, `fecha_compra`, `precio`, `tipo_equipo`, `empleado_id`) VALUES (:equipo_id:, :no_serie:, :marca_id:, :descripcion:, :fecha_compra:, :precio:, :tipo_equipo:, :empleado_id:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\EquipoController.php(29): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:32:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:32:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:33:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:34:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:34:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:39:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:39:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Model.php on line 456.
 1 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 15:46:17 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `equipos...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 15:46:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:46:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-27\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-27\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:46:17 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-27\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-27\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-27\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 15:46:43 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `equipos...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 15:46:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: editar_equipo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:46:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-03\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-03\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 15:46:43 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_inventario`.`equipos`, CONSTRAINT `tipo_equipo_fk` FOREIGN KEY (`tipo_equipo`) REFERENCES `tipo_equipo` (`tipo_equipo`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-03\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-03\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `equipos` SET `equipo_id` = \'234\', `no_serie` = \'5678\', `marca_id` = \'6\', `descripcion` = \'Computadora para recursos humanos\', `fecha_compra` = \'2022-08-03\', `precio` = \'9800.00\', `tipo_equipo` = \'\', `empleado_id` = \'11\'
WHERE `equipos`.`equipo_id` IN (\'234\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `equipos` SET `equipo_id` = :equipo_id:, `no_serie` = :no_serie:, `marca_id` = :marca_id:, `descripcion` = :descripcion:, `fecha_compra` = :fecha_compra:, `precio` = :precio:, `tipo_equipo` = :tipo_equipo:, `empleado_id` = :empleado_id:
WHERE `equipos`.`equipo_id` IN :equipos.equipo_id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\EquipoController.php(62): CodeIgniter\Model->update('234', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EquipoController->editar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EquipoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 17:27:52 --> mysqli_sql_exception: Duplicate entry '26' for key 'PRIMARY' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ma...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ma...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ma...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ma...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\MarcaController.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 17:27:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '26' for key 'PRIMARY'
[Method: POST, Route: agregarMarca]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:27:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '26' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'26\', \'Electronica Panamericana\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'26\', \'Electronica Panamericana\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:27:53 --> [Caused by] mysqli_sql_exception: Duplicate entry '26' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'26\', \'Electronica Panamericana\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'26\', \'Electronica Panamericana\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'26\', \'Electronica Panamericana\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-06 17:28:24 --> mysqli_sql_exception: Duplicate entry '27' for key 'PRIMARY' in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ma...', 0)
#1 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ma...')
#2 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ma...')
#3 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ma...', Array, false)
#4 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\repaso0408\repaso\app\Controllers\MarcaController.php(22): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
#9 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
#10 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\repaso0408\repaso\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 17:28:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '27' for key 'PRIMARY'
[Method: POST, Route: agregarMarca]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:28:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '27' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'27\', \'NovaTech\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'27\', \'NovaTech\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:28:24 --> [Caused by] mysqli_sql_exception: Duplicate entry '27' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'27\', \'NovaTech\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'27\', \'NovaTech\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (\'27\', \'NovaTech\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `marcas` (`marca_id`, `marca`) VALUES (:marca_id:, :marca:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\MarcaController.php(22): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->agregar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:42:14 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/1]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('1')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:42:52 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/7]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('7')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:53:45 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 18:00:45 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 18:00:45 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 18:00:46 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 18:00:46 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 18:00:46 --> TypeError: CodeIgniter\Database\BaseBuilder::getOperatorFromWhereKey(): Argument #1 ($whereKey) must be of type string, int given, called in C:\xampp\htdocs\fs2025\repaso0408\repaso\system\Database\BaseBuilder.php on line 781
[Method: GET, Route: buscar_marca/26]
in SYSTEMPATH\Database\BaseBuilder.php on line 3495.
 1 SYSTEMPATH\Database\BaseBuilder.php(781): CodeIgniter\Database\BaseBuilder->getOperatorFromWhereKey(0)
 2 SYSTEMPATH\Database\BaseBuilder.php(722): CodeIgniter\Database\BaseBuilder->whereHaving('QBWhere', [...], null, 'AND ', true)
 3 SYSTEMPATH\Model.php(925): CodeIgniter\Database\BaseBuilder->where([...])
 4 APPPATH\Controllers\MarcaController.php(36): CodeIgniter\Model->__call('where', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MarcaController->buscar('26')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MarcaController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
